stages:
  - build
  - test
  - optional
  - check

include:
  # Issue check
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

  # Build
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/build@~latest
    inputs:
      anod-args: run build_$ACI_TRACK
      cpus: 16
      image: pe-base
      save-component: true

  # Testing
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: libadalang-tools
      anod-args: run test_$ACI_TRACK
      image: pe-base
      cpus: 16

  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: laltools-gnatfuzz
      anod-args: run test_gnatfuzz_tests
      image: pe-base
      cpus: 8
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          changes:
            paths:
              - src/tgen/**/*
              - src/test-*
              - share/tgen/templates/**/*
            compare_to: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME

  # Optional testing of ALS
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/test@~latest
    inputs:
      job-name: als-test
      anod-args: run test_als_$ACI_TRACK
      image: pe-base
      cpus: 16
      rules:
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: manual
          allow_failure: true
