with C86004a1;
with C86004a2;
with Report; use Report;
procedure C86004a is
begin
   Test
     ("C86004A",
      "CHECK THAT IF A LIBRARY SUBPROGRAM DECLARATION " &
      "IS PRECEDED BY A ""WITH"" CLAUSE FOR A GENERIC " &
      "LIBRARY PROCEDURE M, THEN IN THE BODY OF THE " &
      "SUBPROGRAM, ""STANDARD.M"" IS A " &
      "LEGAL NAME FOR THE GENERIC PROCEDURE");
   C86004a1;
   C86004a2;

   Result;
end C86004a;
