gnatpp --pipe --no-compact b__test069.2.adb
gnatpp --pipe --no-compact b__test069.2.ads
gnatpp --pipe --no-compact b__test070.2.adb
gnatpp --pipe --no-compact b__test070.2.ads
gnatpp --pipe --no-compact csc_channel-version_handling.ads
gnatpp --pipe --no-compact gnatpp_array_formatting.adb
gnatpp --pipe --no-compact gnatpp_exdentation.adb
gnatpp --pipe --no-compact loop_then.adb
gnatpp --pipe --no-compact ors.adb
gnatpp --pipe --no-compact Pretty.adb
gnatpp --pipe --no-compact separate_thens.adb
gnatpp --pipe --no-compact test070.1.ada
gnatpp --pipe --no-compact test070.2.ada
gnatpp --pipe --no-compact test.ada
gnatpp --pipe --no-compact test_gnatpp.1.ada
