

WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY HEADER IS

     PROCEDURE WRONG (WHY : STRING) IS
     BEGIN
          FAILED ("PACKAGE WITH " & WHY & " NOT ELABORATED " &
                  "CORRECTLY");
     END WRONG;

BEGIN

     TEST ("CA5004B", "PRAGMA ELABORATE IS ACCEPTED AND OBEYED " &
                      "EVEN WHEN THE BODY OF THE UNIT NAMED IS " &
                      "MISSING OR OBSOLETE");

END HEADER;
