
WITH REPORT; USE REPORT;
PRAGMA ELABORATE (REPORT);
PACKAGE BODY C94004A_PKG IS

     TASK BODY TT IS
          I : INTEGER := IDENT_INT (120);
     BEGIN
          ACCEPT E;
          COMMENT ("DELAY LIBRARY TASK FOR TWO MINUTES");
          DELAY DURATION(I);
          -- MAIN PROGRAM SHOULD NOW BE TERMINATED.
          RESULT;
     END TT;

END C94004A_PKG;
